# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [2]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch
print(torch.__version__)

# Create random tensor
ts=torch.Tensor(size=(3,3))
# print("\n",)
# print(ts,"\n", ts.dtype,"\n", ts.size,"\n", ts.shape,"\n", ts.ndim)
# print("\n",)

# tensor_77 = torch.randint(low=0, high=10, size=(7, 7))
tensor_77= torch.rand(size=(7,7))
tensor_77

2.11.0+cu128


tensor([[0.8530, 0.3177, 0.8340, 0.3178, 0.3815, 0.5239, 0.2685],
        [0.4879, 0.4258, 0.0742, 0.6960, 0.6595, 0.0184, 0.1459],
        [0.7486, 0.9372, 0.2902, 0.4210, 0.9076, 0.1051, 0.1891],
        [0.6909, 0.7652, 0.0456, 0.1311, 0.0605, 0.7688, 0.7077],
        [0.3519, 0.0969, 0.6074, 0.9365, 0.6475, 0.4312, 0.9821],
        [0.1283, 0.4535, 0.0965, 0.2091, 0.9999, 0.3478, 0.4941],
        [0.1162, 0.2318, 0.8372, 0.4677, 0.8269, 0.2662, 0.8863]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

matmul
mm
@

In [4]:
# Create another random tensor
r= torch.rand(size=(1,7))
print(r)
# Perform matrix multiplication

mul=tensor_77@r.T


tensor([[0.8975, 0.9909, 0.7875, 0.0810, 0.3017, 0.2557, 0.7143]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
torch.manual_seed(12)
# Create two random tensors
a=torch.rand(size=(7,7))
b=torch.rand(size=(1,7))
# Matrix multiply tensors

a@b.T

tensor([[2.0246],
        [2.9553],
        [2.7499],
        [2.0464],
        [2.6388],
        [2.3808],
        [2.1984]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [6]:
# Set random seed on the GPU
# torch.manual_seed(1234)
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [7]:
# Set random seed
torch.cuda.manual_seed(1234)

# Check for access to GPU
print('cuda' if torch.cuda.is_available() else 'cpu')

# Create two random tensors on GPU
tensor_A=torch.rand(size=(2,3)).cuda()
tensor_B=torch.rand(size=(2,3),device=torch.device("cuda"))
print(tensor_A)
print(tensor_B)

cuda
tensor([[0.1342, 0.9405, 0.6803],
        [0.5556, 0.8713, 0.0782]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
mul= tensor_A @ tensor_B.T
mul

tensor([[1.1552, 1.0068],
        [0.8249, 0.6799]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [9]:
# Find max
print(mul.max())
# Find min
print(mul.min())

tensor(1.1552, device='cuda:0')
tensor(0.6799, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [10]:
# Find arg max
print(mul.argmax())

# Find arg min
print(mul.argmin())

tensor(0, device='cuda:0')
tensor(3, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [15]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_1=torch.rand(size=(1,1,1,10))
print(tensor_1, tensor_1.shape)

# Remove single dimensions
tensor_2=tensor_1.reshape(10)
# tensor_2=tensor_2.squeeze()

# Print out tensors and their shapes
print(tensor_2, tensor_2.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
