# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [13]:
# Import torch
import torch
print(torch.__version__)

# Create random tensor
ts=torch.Tensor(size=(3,3))
# print("\n",)
# print(ts,"\n", ts.dtype,"\n", ts.size,"\n", ts.shape,"\n", ts.ndim)
# print("\n",)

# tensor_77 = torch.randint(low=0, high=10, size=(7, 7))
tensor_77= torch.rand(size=(7,7))
tensor_77

2.12.1+cpu


tensor([[0.2666, 0.4481, 0.7936, 0.8548, 0.3510, 0.6052, 0.0390],
        [0.2677, 0.6252, 0.7691, 0.9830, 0.0890, 0.5000, 0.0227],
        [0.2663, 0.8785, 0.5090, 0.7273, 0.4288, 0.4293, 0.2733],
        [0.5921, 0.5528, 0.3829, 0.2338, 0.5268, 0.6913, 0.0425],
        [0.0807, 0.5080, 0.6690, 0.4502, 0.5645, 0.4928, 0.7787],
        [0.5976, 0.1738, 0.6164, 0.8991, 0.3062, 0.7744, 0.9647],
        [0.3303, 0.0938, 0.3264, 0.7257, 0.8234, 0.3400, 0.3332]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

matmul
mm
@

In [15]:
# Create another random tensor
r= torch.rand(size=(1,7))
print(r)
# Perform matrix multiplication 

mul=tensor_77@r.T


tensor([[0.0663, 0.1555, 0.6266, 0.5610, 0.0259, 0.6828, 0.4796]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
torch.manual_seed(12)
# Create two random tensors
a=torch.rand(size=(7,7))
b=torch.rand(size=(1,7))
# Matrix multiply tensors

a@b.T

tensor([[2.0246],
        [2.9553],
        [2.7499],
        [2.0464],
        [2.6388],
        [2.3808],
        [2.1984]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed


# Check for access to GPU

# Create two random tensors on GPU



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B


### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max

# Find min


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max


# Find arg min



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed


# Create random tensor


# Remove single dimensions


# Print out tensors and their shapes
